# config.yaml

url: testurl
rkuser: rkuser
passwd: rkpwd
chain: test-chain
port: testport
stream: streamname
testdata: test_data
amount: test_amount
dumptxid: test_txid
privatekey: test_privkey
validaddress: valid_address
invalidaddress: invalid_address
miningaddress: mining_address
nonminingaddress: nonmining_address
multisigaddress: multisig_address
wrongimportaddress: wrongimport_address
mainaddress: main_address
permissionaddress: permission_address
dumptxhex: dump_txhex
dumpsignedtxhex: dump_signedtxhex
samplegetmultisigaddress: sample_multisigaddress
samplemerkleroot: sample_merkleroot
sampleblockhash: sample_blockhash
sampledata: sample_data
sampletransac: sample_transaction_id
transactionid: transaction_id
sampletxid: sample_txid
